adds link-url
jkk/verily pull request #11
Opened 2016-12-28 19:19 UTC by timothypratley

Proposal: Allow //example.com to be a valid url (no http(s): in front of it) #9

2016-12-29 00:09 UTC, iku000888 requested changes

2016-12-29 00:09 UTC, iku000888 commented on src/cljx/jkkramer/verily.cljx
> -                          ;; TODO: better cljs impl
I feel a bit more comfortable leaving this comment here.

2016-12-29 00:09 UTC, iku000888 commented on src/cljx/jkkramer/verily.cljx
> -                          ;; TODO: better cljs impl
I feel a bit more comfortable leaving this comment here.

2016-12-29 00:10 UTC, iku000888 commented
Thanks for the PR!
I presume this covers #10 ?
I will merge this once the comment is added back.

2016-12-29 01:00 UTC, timothypratley commented on src/cljx/jkkramer/verily.cljx
> -                          ;; TODO: better cljs impl
okidoki, I've added it back in (see below)

2016-12-29 03:28 UTC, merged

2017-01-11 23:44 UTC, iku000888 commented
@timothypratley 
Made a release with the changes.
Would much appreciate if you can sanity check that your changes are included.
Thanks.

https://clojars.org/jkkramer/verily/versions/0.6.1

2017-03-20 06:42 UTC, timothypratley commented
works great for me, thanks! (sorry for the slow reply)

2017-03-20 23:53 UTC, iku000888 commented
:+1: 
If you have any other enhancements, please do not hesitate to share :)